#dev

#dev
server:
  port: 11302

spring:
  datasource:
    url: jdbc:hsqldb:file:./db/buff.db
    username: sa
    password: sa
    driverClassName: org.hsqldb.jdbcDriver

netty:
  host: 127.0.0.1
  proxy: 
    - input: 127.0.0.1:1000
      output: 127.0.0.1:1029,127.0.0.1:1028
logging:
  config: file:./config/log4j2.xml

debug: false